[custom.all.async]
type = "local"
path = "."
ipkg = "async.ipkg"
test = "test/test.ipkg"

[custom.all.async-epoll]
type = "local"
path = "async-epoll"
ipkg = "async-epoll.ipkg"

[custom.all.async-docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

[custom.all.epoll]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-epoll"
commit = "latest:main"
ipkg   = "epoll.ipkg"

[custom.all.ref1]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ref1"
commit = "latest:main"
ipkg   = "ref1.ipkg"

[custom.all.array]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"
